### ISSUE TITLE
llama3.1   function call

### ISSUE THREAD

**Issue by icetech233** [tryAGI/Ollama#13]

**Comment by HavenDV** [comment]
I added tools and Source Generator support for this, you can take a look at it here: https://github.com/tryAGI/Ollama/blob/main/src/tests/Ollama.IntegrationTests/Tests.Integration.cs#L180
https://github.com/tryAGI/Ollama/blob/main/src/tests/Ollama.IntegrationTests/WeatherFunctions.cs
You can also define tools manually if you want.

But maybe some testing is still needed here

**Comment by HavenDV** [comment]
I also added support for automatically calling tools for client.Chat(), you can see an example in the README.
