### ISSUE TITLE
Support for options in API calls

### ISSUE THREAD

**Issue by aplex** [tryAGI/Ollama#43]
First of all, thanks for building this great library! 

## What would you like to be added:
Ollama REST API can accept a bunch of options, like context window length, temperature, etc. Would be great to expose them in this library as well. 

Options list: https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-chat-completion

## Why is this needed:

The main option I want to change is the size of context window (num_ctx), as the default is very small.

**Comment by HavenDV** [comment]
![image](https://github.com/user-attachments/assets/f2046683-a84f-403e-a08b-c4aea7300054)
I think it's already here, this is exactly one of the meanings for the client to be generated and we support all possible options automatically. Check the GenerateChatCompletionAsync options parameter.
But maybe you mean using all options within the Chat class, I'll add it now

**Comment by HavenDV** [comment]
I also added the ability to specify format/options/keepAlive when using Chat() in version 1.9.0

**Comment by aplex** [comment]
Works great, thanks!
