### ISSUE TITLE
how to Generate  openapi code?

### ISSUE THREAD

**Issue by icetech233** [tryAGI/Ollama#7]
### Describe the bug

/main/src/libs/Ollama/Generated/net8.0/OpenApiGenerator

### Steps to reproduce the bug

1

### Expected behavior

1

### Screenshots

1

### NuGet package version

1

### Additional context

1

**Comment by HavenDV** [comment]
It uses [C# Source Generators](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview) so just rebuild project
But OpenApiGenerator also have cli - https://github.com/HavenDV/OpenApiGenerator/tree/main?tab=readme-ov-file#cli
