### ISSUE TITLE
An error occurs when executing the "Tool" example, the type does not match

### ISSUE THREAD

**Issue by coocms** [tryAGI/Ollama#80]
### Describe the bug

An error occurs when executing the "Tool" example, the type does not match.

Error Message:

Unable to convert from 'System.Collections.Generic.IList<CSharpToJsonSchema.Tool>' to 'System.Collections.Generic.IList<Ollama.Tool>'

### Steps to reproduce the bug

Follow the "Tool" examples to write code

### Expected behavior

Follow the example and execute normally

### Screenshots

![image](https://github.com/user-attachments/assets/b3065327-70be-4dec-ba7b-dada05a9746d)

![image](https://github.com/user-attachments/assets/72d18bcf-e83e-4fc8-b367-5540c13c4210)

![image](https://github.com/user-attachments/assets/c374a02d-3f87-49ac-a4d5-3d089a7c0bc2)

![image](https://github.com/user-attachments/assets/2e6edf7e-0ac7-438a-80ae-69f8be2de7bd)

### NuGet package version

1.13.0

**Comment by HavenDV** [comment]
Hi. Please use `service.AsTools().AsOllamaTools()`

**Comment by coocms** [comment]
@HavenDV It works. Thanks.
